### ISSUE TITLE
curl: (7) Couldn't connect to server - unzip:  cannot find or open /home/user/.asdf...

### ISSUE THREAD

**Issue by torgeirak** [asdf-vm/asdf-elixir#112]
Going through the installation of elixir through .asdf. I have installed .asdf and erlang 24.0.5
The folder "/home/user/.asdf/downloads/elixir/1.12.2-otp-24/" exists, but as far as I can see there is currently no "elixir-precompiled-1.12.2-otp-24.zip"-file present. Not sure if there should be. I have installed unzip.

$ asdf install elixir 1.12.2-otp-24
==> Checking whether specified Elixir release exists...
==> Downloading 1.12.2-otp-24 to /home/user/.asdf/downloads/elixir/1.12.2-otp-24/elixir-precompiled-1.12.2-otp-24.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server
==> Copying release into place
unzip:  cannot find or open /home/user/.asdf/downloads/elixir/1.12.2-otp-24/elixir-precompiled-1.12.2-otp-24.zip, /home/user/.asdf/downloads/elixir/1.12.2-otp-24/elixir-precompiled-1.12.2-otp-24.zip.zip or /home/user/.asdf/downloads/elixir/1.12.2-otp-24/elixir-precompiled-1.12.2-otp-24.zip.ZIP.

**Comment by Stratus3D** [comment]
It seems to work for me:

```
asdf install elixir 1.12.2-otp-24
==> Checking whether specified Elixir release exists...
==> Downloading 1.12.2-otp-24 to /Users/trevorbrown/.asdf/downloads/elixir/1.12.2-otp-24/elixir-precompiled-1.12.2-otp-24.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6017k  100 6017k    0     0  6716k      0 --:--:-- --:--:-- --:--:-- 6708k
==> Copying release into place
```

It looks like a network blip. What happens if you re-install? `asdf uninstall elixir 1.12.2-otp-24` followed by `asdf install elixir 1.12.2-otp-24`

**Comment by Stratus3D** [comment]
Closing due to lack of a response.
