### ISSUE TITLE
Errors when attempting to install 1.3.0

### ISSUE THREAD

**Issue by Qqwy** [asdf-vm/asdf-elixir#12]
When attempting to install Elixir 1.3.0 using the ASDF package manager (with the asdf-elixir plugin), I get the following error:

```
asdf install elixir 1.3.0
/tmp/tmp.jhDRGP3Gto/elixir-precompiled-1.3.0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21    0    21    0     0     36      0 --:--:-- --:--:-- --:--:--    36
[/tmp/tmp.jhDRGP3Gto/elixir-precompiled-1.3.0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/tmp.jhDRGP3Gto/elixir-precompiled-1.3.0.zip or
        /tmp/tmp.jhDRGP3Gto/elixir-precompiled-1.3.0.zip.zip, and cannot find /tmp/tmp.jhDRGP3Gto/elixir-precompiled-1.3.0.zip.ZIP, period.

```

**Comment by HashNuke** [comment]
@Qqwy There's only 1.3.0-rc.0 available https://github.com/elixir-lang/elixir/releases

**Comment by Qqwy** [comment]
The thing is, that `asdf list-all elixir` lists the new `1.3.0` in its list of possible version numbers. Which is why I attempted to download `1.3.0` instead of `1.3.0-rc.0`.

**Comment by HashNuke** [comment]
@Qqwy Thanks for reporting with details. This is definitely a bug. 1.3.0 shouldn't be listed there.
I've created a new issue to track this https://github.com/asdf-vm/asdf-elixir/issues/13
We will fix this soon. In the mean time the following will work for you:

```
asdf install elixir 1.3.0-rc.0
```
