### ISSUE TITLE
curl: (60) server certificate verification failed

### ISSUE THREAD

**Issue by leonardorame** [asdf-vm/asdf-elixir#133]
Hi, when trying to install elixir with:

`asdf install elixir 1.16.0-otp-26`

I got this error:

`curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`

The solution was to edit the file ~/.asdf/plugins/elixir/bin/install and appending -k to all the curl references, lines (87,  107, 117, 138). For example on line 87 there was:

`http_status=$(curl -L -I -w '%{http_code}' -s -o /dev/null "$download_url")`

and now:

`http_status=$(curl -k -L -I -w '%{http_code}' -s -o /dev/null "$download_url")`

This way I was able to install it.

**Comment by Stratus3D** [comment]
`-k` allows an insecure connection, which isn't something I'd recommend. It appears there is either something wrong with the certs you have locally on your machine (are they out of date?) or the server that Elixir was downloaded from (maybe a cert expired briefly and they didn't have it set to auto renew?).

In any case there is nothing that should be done in asdf-elixir for this. Closing this issue.
