### ISSUE TITLE
Update PATH for escripts

### ISSUE THREAD

**Issue by rockwood** [asdf-vm/asdf-elixir#17]
I was wondering if there's a recommended way to automatically update PATH with the escripts directory of the current elixir version. 

Right now, I'm manually adding `.asdf/installs/elixir/1.3.0-rc.1/.mix/escripts` to my PATH, but it would be really cool if that happened automatically when switching versions.

Also, asdf rocks. Great work!

**Comment by vic** [comment]
That's now in master 🎉   

Thanks for your suggestion!

https://github.com/asdf-vm/asdf-elixir/blob/master/README.md#elixir-escripts-support
