### ISSUE TITLE
Unexpected behavior with Elixir 1.3.4 distribution

### ISSUE THREAD

**Issue by mdowell12** [asdf-vm/asdf-elixir#23]
Hello!  I've seen some unexpected behavior from the `elixir` binary that comes with the 1.3.4 distribution.  The below issue has a complete description of the problem:

https://github.com/elixir-lang/elixir/issues/5686

The issue was resolved when I switched to the binary from the elixir repository.

**Comment by vic** [comment]
Hm, binaries are those built by the *official* [Bob builder](https://github.com/hexpm/bob), I'm closing this, try using the latest asdf-elixir master branch and reopen if needed.
