### ISSUE TITLE
Fail on elixir install

### ISSUE THREAD

**Issue by jhonathas** [asdf-vm/asdf-elixir#29]
$ asdf install elixir 1.4.2

/var/folders/h_/6v1myq556nd58yrl567k7gjh0000gn/T//elixir-precompiled-1.4.2.zip
** Resuming transfer from byte position 3796516
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

This error occurs in any version of the elixir. I already installed erlang, node and postgres without problem.

**Comment by keithmattix** [comment]
For some reason, asdf isn't cleaning up the partial zip file of a download. `cd` into the directory and remove the zip file and see if that helps your issue

**Comment by harmon25** [comment]
also having this issue with new 1.5.3.
Folder appears to be in /tmp but ASDF cannot unzip it...

**Comment by kamidev** [comment]
1.5.3 doesn't work for me either. This is the message I get:

/var/folders/1w/2g6wlyyd67x8l_vspn1nryl40000gn/T//elixir-precompiled-1.5.3.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243    0   243    0     0    118      0 --:--:--  0:00:02 --:--:--   118
[/var/folders/1w/2g6wlyyd67x8l_vspn1nryl40000gn/T//elixir-precompiled-1.5.3.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

**Comment by Stratus3D** [comment]
I am not able to replicate this issue now. Is there still a problem with this?

**Comment by jhonathas** [comment]
Sorry I have not returned. I deleted the elixir plugin and installed it again and it worked.

**Comment by Stratus3D** [comment]
I don't think this is an issue anymore, but the output of the plugin could be improved. Follow issue #18, PR #19 for improvements.
