### ISSUE TITLE
Using Elixir master branch

### ISSUE THREAD

**Issue by lpil** [asdf-vm/asdf-elixir#30]
Hello!

I've [a project](https://github.com/lpil/exfmt) that depends on Elixir features that are not released.

Is there a recommended way for managing a manually installed Elixir version alongside the asdf installed versions?

Cheers,
Louis

**Comment by vic** [comment]
Hey @lpil 

Sure, asdf supports installing elixir from any branch (both, `bob` precompiled or built on your machine from source). 

```shell
# install latest branch commit (precompiled by hexpm's bob) 
# replace `master` with any branch name
# for updating it, just uninstall and reinstall it again.
asdf install elixir master-otp-20

# or building from source on your machine
# this will clone the code inside ~/.asdf/installs/elixir/_version_
# You replace `master` with any commit sha.
# be sure to be using erlang-20.0 for latest elixir 1.5
asdf install elixir ref:master 

# If you already have your own elixir development version
# say, you are contributing to the language and have some
# code no other has already built at a custom location, say
# ~/projects/hackish-elixir
ln -s ~/projects/haskish-elixir ~/.asdf/installs/elixir/haskish
asdf local elixir hackish
```

Hope this helps

**Comment by lpil** [comment]
That's wonderful, thank you!

Is this documented somewhere? I failed to find it but that's probably my bad :)

**Comment by vic** [comment]
Yep, the README on this repo [mentions](https://github.com/asdf-vm/asdf-elixir/#elixir-precompiled-versions) about bob precompiled packages, one thing that maybe is not immediately obvious is that we actually use bob's packaging naming convention. So anything you give to asdf-elixir we will just request to bob. 

Regarding `ref:` versions, that's [documented on asdf](https://github.com/asdf-vm/asdf) README itself.

And the last one (just linking your custom directory) is just a trick, documented nowhere I guess.

Feel free to submit a PR if you feel like documentation could be clearer on this. (Also I'm not a native english speaker so I guess  sometimes the docs I write reflect that and maybe are not as clear as they could be).

**Comment by lpil** [comment]
Thank you! :)
