### ISSUE TITLE
Not able to switch to an old otp version

### ISSUE THREAD

**Issue by martinos** [asdf-vm/asdf-elixir#34]
I have installed version  1.4.5 with otp 18 and it seems that I am still using the latest version of otp.
```
$ asdf local elixir 1.4.5-otp-18
$ mix -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Mix 1.4.5
```
It seems that OTP 20 is loaded instead of 18.

**Comment by martinos** [comment]
Sorry I should have better read the documentation.  I think it would be great to have an error message telling the user to install the corresponding version of Erlang/OTP using asdf.

**Comment by vic** [comment]
Hey feel free to submit a PR to improve the README regarding that matter. 

I'm closing this now.
