### ISSUE TITLE
How to install elixir 1.6 ?

### ISSUE THREAD

**Issue by collegeimprovements** [asdf-vm/asdf-elixir#40]

**Comment by schlenks** [comment]
I'm not sure if it's _currently_ possible since asdf-elixir looks at `https://api.github.com/repos/elixir-lang/elixir/releases` for it's list of versions available. Until 1.6 has a release available on Github, it won't show up there.

**Comment by bokay** [comment]
You can use `ref` feature from `asdf`.

For instance, to install the version from the commit `6915de35a61838ac32c4adcb0e47986b3c6e71c1`, you would do:
`asdf install elixir ref:6915de35a61838ac32c4adcb0e47986b3c6e71c1`
and to set it locally on a project
`asdf local elixir ref-6915de35a61838ac32c4adcb0e47986b3c6e71c1`

Happy ~formatting~ coding!

**Comment by johnhamelink** [comment]
@bokay thanks for this, I turned your comment into a PR https://github.com/asdf-vm/asdf-elixir/pull/41

**Comment by axelson** [comment]
Is anyone else having trouble installing 1.6.0? `list-all` shows 1.6.0 just fine but when I run `asdf install elixir 1.6.0` I get an `<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>` error.

Actually it looks like `asdf install elixir 1.6` works fine. But I would expect `1.6.0` to work as well since that's what is tagged: https://github.com/elixir-lang/elixir/releases/tag/v1.6.0

**Comment by goofansu** [comment]
@axelson `asdf install elixir 1.6.0` is no problem. I installed it the day it released.

**Comment by axelson** [comment]
Yeah it looks like it works now. Just wasn't when I tried.

**Comment by mcelaney** [comment]
I'm getting a strange error installing 1.6.4
<details>
$ asdf install elixir 1.6.4
/var/folders/pq/9xbmdz9s1ml2q1rqmy4fr6_w0000gn/T//elixir-precompiled-1.6.4.zip
** Resuming transfer from byte position 243
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
[/var/folders/pq/9xbmdz9s1ml2q1rqmy4fr6_w0000gn/T//elixir-precompiled-1.6.4.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/pq/9xbmdz9s1ml2q1rqmy4fr6_w0000gn/T//elixir-precompiled-1.6.4.zip or
        /var/folders/pq/9xbmdz9s1ml2q1rqmy4fr6_w0000gn/T//elixir-precompiled-1.6.4.zip.zip, and cannot find /var/folders/pq/9xbmdz9s1ml2q1rqmy4fr6_w0000gn/T//elixir-precompiled-1.6.4.zip.ZIP, period.
</details>

**Comment by goofansu** [comment]
You can see the download url in bin/install script. The precompiled package
should be under https://repo.hex.pm but is absent now.

**Comment by bigardone** [comment]
Same issue here as @mcelaney while trying to install 1.6.4

```
➜ asdf install elixir 1.6.4
/var/folders/z7/nr3g6g2n743gnr5n46czv3880000gn/T//elixir-precompiled-1.6.4.zip
** Resuming transfer from byte position 243
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
[/var/folders/z7/nr3g6g2n743gnr5n46czv3880000gn/T//elixir-precompiled-1.6.4.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/z7/nr3g6g2n743gnr5n46czv3880000gn/T//elixir-precompiled-1.6.4.zip or
        /var/folders/z7/nr3g6g2n743gnr5n46czv3880000gn/T//elixir-precompiled-1.6.4.zip.zip, and cannot find /var/folders/z7/nr3g6g2n743gnr5n46czv3880000gn/T//elixir-precompiled-1.6.4.zip.ZIP, period.
```

**Comment by goofansu** [comment]
I confirm 1.6.4 can install correctly now.

**Comment by bigardone** [comment]
Me too! 💪

**Comment by vic** [comment]
Looks like it was due to pre-compiled Elixir package was not available from Bob at the time you tried to install. We have some PR regarding better 404 handling, having those would provide a better error in these cases. (I'll try to take a look at them and merge on this weekend).

I guess we can close this issue now. :)
