### ISSUE TITLE
Consider adding rebar and rebar3 from `mix local.rebar` in shims

### ISSUE THREAD

**Issue by victorolinasc** [asdf-vm/asdf-elixir#44]
When building anything that depends on an erlang library, mix uses rebar (most of the time). It would be incredibly useful to have rebar and rebar3 in the shims folder for debugging failing builds.

**Comment by akoutmos** [comment]
I had a similar issue in that I needed rebar3 to compile something. But then I noticed that there is an asdf plugin specifically for rebar https://github.com/Stratus3D/asdf-rebar. Hopefully that helps.

**Comment by Stratus3D** [comment]
@victorolinasc that makes sense. Mix installs it's own rebar right? We'd just need to make it available? This seems like a good enhancement.

**Comment by vanvoljg** [comment]
I agree, this would be a useful feature.

https://github.com/asdf-vm/asdf-elixir/issues/32#issuecomment-430641925 would be a good solution. Or... so would adding `.mix` to `list-bin-paths` to force shim creation of those binaries.

I actually favor the latter approach because it doesn't further pollute the PATH. Are you aware of any reasons it wouldn't work to do this? I'm happy to send up a pull request.

**Comment by ericmj** [comment]
I don't think that this should be added to asdf. I would not expect installing elixir to also install non-elixir binaries. The rebar that elixir installs with `mix local.rebar` is for internal use to compile rebar dependencies and it is usually outdated compared to the latest rebar release. If you wish to use rebar yourself I would suggest installing it using the official channels for rebar. If you wish to debug builds of dependencies I think it would be better to temporarily add `.mix` to `PATH` or to invoke rebar it with the full path.

**Comment by vanvoljg** [comment]
Ahh, there ARE some reasons! Thanks for the insight, Eric.

I figured poking this would make something happen, and learning more about the inner workings is a good something.

Cheers!

**Comment by Stratus3D** [comment]
I don't feel too strongly about this either way, but @ericmj has a good point and I don't see much practical value in exposing Elixir's `rebar` and `rebar3` commands as shims. If you do need your own version of rebar in an Elixir project for some reason I suggest you use my rebar plugin - https://github.com/Stratus3D/asdf-rebar.
