### ISSUE TITLE
feature request: allow for building from source with kiex

### ISSUE THREAD

**Issue by Trevoke** [asdf-vm/asdf-elixir#46]
I'd like to use tools like elixir-ls for my editor, but they rely on the language being compiled from source on the machine.

Since asdf-erlang compiles from source with kerl, I can use elixir-ls to go to the source code of an Erlang symbol. Since asdf-elixir provides precompiled versions only, as far as I know, I can't use it to go to the source code of the Elixir stdlib.

Thanks.

**Comment by vic** [comment]
asdf-elixir has never been limited to installing just precompiled versions, it's the default, but actually you can also install from a source repo. For example, you can have a custom experimental Elixir version (if you are hacking on Elixir itself). I've just merged a couple of PRs that hopefully make it clearer how to install a non precompiled version. If you still have some questions, feel free to ask. :)

**Comment by Trevoke** [comment]
Oh that's cool, thanks! Does this work tags, too, or just commit references?

**Comment by Trevoke** [comment]
Hi @vic -- can I pass custom configuration options such as +debug_info ?

**Comment by Stratus3D** [comment]
@Trevoke yes, refs include tags, branches, and commit shas.
