### ISSUE TITLE
Dialyxir Problems

### ISSUE THREAD

**Issue by javajolt** [asdf-vm/asdf-elixir#51]
When I used the pre-built versions of Elixir, I have problems running dialyzer:
```
:dialyzer.run error: Analysis failed with error:
Could not scan the following file(s):
  Could not get Core Erlang code for: /Users/hazen/.asdf/installs/elixir/1.7.3/lib/elixir/ebin/elixir_parser.beam
  Recompile with +debug_info or analyze starting from source code  Could not get Core Erlang code for: /Users/hazen/.asdf/installs/elixir/1.7.3/lib/elixir/ebin/elixir_utils.beam
```
It looks like I need to build with the `+debug_info` flag, but when I look at the source it's not clear what the mechanism is to do that.  Is there simply a flag I can pass in?

**Comment by dbernheisel** [comment]
@javajolt do you have Erlang also installed? If not, try installing it and trying again. Any Elixir projects I have, I often also include the erlang version in my `.tool-versions` file.

**Comment by javajolt** [comment]
Thanks! Turns out we needed to have the proper `MIX_ENV` set. It was missing some of our code otherwise.
