### ISSUE TITLE
ERROR: unzip not found

### ISSUE THREAD

**Issue by LeandroRezendeCoutinho** [asdf-vm/asdf-elixir#53]
Manjaro linux
Fish shell

After instaling erlang with asdf

asdf install elixir 1.7.3                                                                                                                                            

1 :( 10/17/18 -  2:17 
/tmp/elixir_build_9BG4H2/elixir-precompiled-1.7.3.zip                                                                                                                                        
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                              
                                 Dload  Upload   Total   Spent    Left  Speed                                                                                                                
100 5229k  100 5229k    0     0  6094k      0 --:--:-- --:--:-- --:--:-- 6087k                                                                                                               
ERROR: unzip not found

**Comment by Stratus3D** [comment]
Unzip is not installed on you computer. You'll need to install it in order to use the plugin. We should probably document this dependency in the readme.

**Comment by Fl4m3Ph03n1x** [comment]
I created a PR to help fix this. Please review:
https://github.com/asdf-vm/asdf-elixir/pull/58
