### ISSUE TITLE
Running mix gives an exec: erl: not found error

### ISSUE THREAD

**Issue by rbfonbuena** [asdf-vm/asdf-elixir#60]
Did the following steps successfully:
```
$ asdf install erlang 21.2.3
$ asdf install elixir 1.8.0

$ asdf global erlang 21.2.3
$ asdf global elixir 1.8.0
```
but getting an error when running `mix`, is there a step I'm missing?

![image](https://user-images.githubusercontent.com/30283493/51595320-66cbc680-1f31-11e9-8324-aedbb2c4d7ff.png)

**Comment by rbfonbuena** [comment]
Your suggestion worked, thank you.

**Comment by rubemz** [comment]
I'm getting this error too. Is there a fix for this problem, besides the workaround?

**Comment by Stratus3D** [comment]
@rubemz what version of asdf are you using? Try upgrading to the latest version and see if that fixes the issue. `asdf reshim` may also help.

**Comment by webhive** [comment]
Confirm! Exactly the same issue for me

**Comment by tfwright** [comment]
I'm having this problem trying to run an elixir app as a systemd service.

```
$ asdf --version
v0.7.1
$ cat .tool-versions 
erlang 22.1.8
elixir 1.9
```

**Comment by izzues** [comment]
Same issue!
```
$ asdf --version
v0.7.8-4a3e3d6
$ cat .tool-versions
erlang 22.3.2
elixir 1.10.2-otp-22
```
On Arch Linux, if that makes any difference.

**Comment by Stratus3D** [comment]
@tfwright can you confirm you have erlang installed? What happens if you run `type -a erl`?

**Comment by vanderhoop** [comment]
For anyone else who runs into issues with the above command, I had to update the URL to what GitHub cites as the clone address. This worked for me:

```
git clone -b v0.6.3 --single-branch https://github.com/asdf-vm/asdf.git ~/.asdf
```

**Comment by Stratus3D** [comment]
This should not be an issue with the latest version of asdf (version `0.8.0`).

**Comment by crokobit** [comment]
still failed after `asdf reshim`. Using asdf version 0.8.0.

**Comment by smorimoto** [comment]
This seems to be an issue only with macOS. This has not occurred, at least in testing with Ubuntu.

**Comment by smorimoto** [comment]
This should be reproduced with #96.

**Comment by davidalejandroaguilar** [comment]
> still failed after `asdf reshim`. Using asdf version 0.8.0.

Same here:

```
➜  asdf --version 
v0.8.0
➜  asdf current elixir
elixir          1.10.0-otp-22   /Users/david/.tool-versions
➜  asdf current erlang
erlang          22.3.1          /Users/david/.tool-versions
```

On MacOS Catalina 10.15.7

**Comment by Ryanauger95** [comment]
Same issue here on Mac Monterrey :/

**Comment by volkerholloh** [comment]
+1 with this issue on Monterrey

**Comment by f-francine** [comment]
I am getting this same error when I try to run any mix command.
I am using ubuntu 20.10

It used to work perfectly, but than I had to remove and reinstall the erlang plugin and this problem started to happen

**Comment by crokobit** [comment]
same issue here.

**Comment by SalvatoreT** [comment]
I think this has been resolved for macOS 12.6.1 (Monterey).

```shell
❯ asdf --version
v0.10.2
```

```shell
❯ asdf plugin list --refs --urls
elixir                       https://github.com/asdf-vm/asdf-elixir.git master 1693b35
erlang                       https://github.com/asdf-vm/asdf-erlang.git master 26ba0a0
```

```shell
❯ asdf current
elixir          1.14.2          
erlang          25.1.2          
```

And it works!

```shell
❯ mix --version
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Mix 1.14.2 (compiled with Erlang/OTP 23)
```

**Comment by skull-squadron** [comment]
Not working on CentOS 9 Stream in 2024. `/opt/asdf/installs/elixir/1.16.2-otp-26/bin/elixir: line 247: exec: erl: not found`

**Comment by dustinaleksiuk** [comment]
I'm getting this with Ubuntu 24.04.01 if I try to run `elixir -v`. If I just type `erl` on the command line it is found, and I see it in my shims folder.

**Comment by dzintars** [comment]
Just leaving it there.
All I needed was to add `asdf` plugin to my oh-my-zsh (because I use ZSH with OMZSH). 

```conf
plugins=(
  asdf
)
```

Or, I think, you could do the same just by sticking `. $HOME/.asdf/asdf.sh` in your `.zshrc`

**Comment by hermanius** [comment]
In my case I had set my PATH environment variable to ~/.asdf/shims:$PATH.
By changing it to an absolute path like /home/elixir/.asdf/shims it solved the problem.
(Where elixir is the user I have created for working on elixir projects)

**Comment by olezhek** [comment]
> In my case I had set my PATH environment variable to ~/.asdf/shims:$PATH. By changing it to an absolute path like /home/elixir/.asdf/shims it solved the problem. (Where elixir is the user I have created for working on elixir projects)

same with me
