### ISSUE TITLE
Install Erlang with OTP PATCH version specified?

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [asdf-vm/asdf-elixir#68]
Greetings,
I'm trying to install elixir 1.9 with a specific (well, greater than) version of OTP. OTP-22 is not enough, due to a bug in [Erlang 22.0.4](https://github.com/jeremyjh/dialyxir/issues/343) dialyxir fails, unless OTP is 22.0.5 (or greater)

Is there any solution to this?

**Comment by Stratus3D** [comment]
Are you asking about version `1.9.0-otp-22`? The otp version is the verision Elixir was compiled against when the package was created. You can still specify the specific Erlang version you want to use in the `.tool-versions` file. Something like this should do what you need:

```
erlang 22.0.5
elixir 1.9.0-otp-22
```

**Comment by Fire-Dragon-DoL** [comment]
Oh ok, so it's sufficient to specify the erlang version. Thanks!
