### ISSUE TITLE
Cannot use Elixir compiled from source in local machine

### ISSUE THREAD

**Issue by goofansu** [asdf-vm/asdf-elixir#72]
I have Elixir master branch compiled in directory `/Users/james/src/elixir`. It fails with error `asdf: No version set for command mix`.

```
$ asdf local elixir path:/Users/james/src/elixir
$ asdf current
elixir         path:/Users/james/src/elixir (set by /Users/james/src/elixir_formatter_playground/.tool-versions)
$ mix
asdf: No version set for command mix
you might want to add one of the following in your .tool-versions file:

elixir 1.9.4-otp-22
$ asdf list elixir
  1.9.4-otp-22
```

asdf version: 0.7.5
asdf-elixir git-hash: fa76a3673

**Comment by Stratus3D** [comment]
Sorry for the late reply. This is a known bug. See https://github.com/asdf-vm/asdf/issues/559

**Comment by goofansu** [comment]
@Stratus3D Sorry I missed that ticket. Closed.
